### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by caelinsutch** [leisim/logger#48]
I'm getting no log output.

pubspec.yaml
```
environment:
  sdk: ">=2.1.0 <3.0.0"
...
dependencies
  logger: 0.9.1
```

main.dart
```
main() {
  var logger = Logger();

  logger.e("Logger is working!");
  print("logger");
}
```

"Logger is working" doesn't print, but "logger" does.

**Comment by caelinsutch** [comment]
Note, running with `dart --enable-asserts example/main.dart` works. Is this required? If so, it should be noted in the documentation.

**Comment by haarts** [comment]
The default logger as you are using it uses the [`DevelopmentFilter`](https://pub.dev/documentation/logger/latest/logger/DevelopmentFilter-class.html) (see https://pub.dev/documentation/logger/latest/logger/Logger/Logger.html). That filter doesn't log anything in "production" mode, this is defined as not using asserts. Running a program with the `dart` interpreter w/o arguments does not use asserts/run the program in production mode. The README explains this too: https://github.com/leisim/logger#logfilter

I hope this helps.

**Comment by rubenvereecken** [comment]
This was far, far too hidden, and we spent far, far too much time finding it. Thanks, will give this a try.

It's a strange construction though, do I really need to use a different filter depending on whether the app is in dev/prod? The default is DevelopmentFilter. Since we use a FileOutput, we very much want to log in production, so we can generate a log file for reporting in release.

**Comment by CBeening** [comment]
This indeed was too hidden and unexpected behaviour.
The main reason for using such a logger would probably be to get logs during production.

If I only want them while developing I might aswell use print everywhere.

Using ProductionFilter for everything now aswell.
