### ISSUE TITLE
how to delete the log title

### ISSUE THREAD

**Issue by kamike** [leisim/logger#50]
I want to remove the title of the log to save space.
I set printTime: false,It look like doesn't  work, what should I do?

![image](https://user-images.githubusercontent.com/3920019/83711596-397b4680-a656-11ea-8732-c0e8f417dc5f.png)

![image](https://user-images.githubusercontent.com/3920019/83711163-0ab0a080-a655-11ea-92f9-30b74480b911.png)

Another problem is that if there are spaces in the console, garbled characters will appear.
This library is very useful, do not want to give it up,Please give me some suggestions, thank you very much!!

logger: ^0.9.1
flutter sdk: ">=2.7.0 <3.0.0"

**Comment by haarts** [comment]
Responding to the numbered boxes you have in the first screenshot:
1. This is from Flutter itself. There's nothing we can do about that. You'll notice that this only happens when outputting to a console. With a file output this is gone.
2. This is because Android Studio (or some other IDE like VSCode) do not understand ASCII escape codes. Please read this how to solve it: https://github.com/leisim/logger/#colors
3. Same issue as above. This is the ASCII escape code to reset colors. 

You can further tweak the output of the PrettyPrinter with the [constructor arguments](https://pub.dev/documentation/logger/latest/logger/PrettyPrinter/PrettyPrinter.html).

I'm closing the issue if this doesn't help you please feel free to reopen.
